FROM node:18-alpine

# Define timezone para evitar problemas com cron e MySQL
ENV TZ=America/Sao_Paulo

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

# Agora o entrypoint é o server.js (API + controle do cron)
CMD ["node", "server.js"]